apiVersion: apps/v1
kind: Deployment
metadata:
  name: visor
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: visor
  template:
    metadata:
      labels:
        app: visor
    spec:
      containers:
      - name: visor
        image: visor-service:20250606-114533
        ports:
        - containerPort: 5000
