{{- if .Values.services.distanceMonitor.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: distance-monitor
  namespace: {{ .Values.namespace }}
  labels:
    app: distance-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: distance-monitor
  template:
    metadata:
      labels:
        app: distance-monitor
    spec:
      containers:
      - name: distance-monitor
        image: "{{ .Values.services.distanceMonitor.image.repository }}:{{ .Values.services.distanceMonitor.image.tag }}"
        ports:
        - containerPort: 5000
        env:
        - name: VEHICLE_ID
          value: "{{ .Values.namespace }}"
        - name: RABBITMQ_HOST
          value: "rabbitmq.{{ .Values.rabbitmq.namespace }}.svc.cluster.local"
        - name: RABBITMQ_USER
          valueFrom:
            secretKeyRef:
              name: rabbitmq-credentials
              key: username
        - name: RABBITMQ_PASS
          valueFrom:
            secretKeyRef:
              name: rabbitmq-credentials
              key: password
---
apiVersion: v1
kind: Service
metadata:
  name: distance-monitor
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: distance-monitor
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: ClusterIP
{{- end }}
