apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  username: {{ .Values.rabbitmqCredentials.username }}
  password: {{ .Values.rabbitmqCredentials.password }}
