apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kong-ingress
  namespace: backend
  annotations:
    kubernetes.io/ingress.class: kong
    konghq.com/strip-path: "false"   # strip /api from request path when forwarding
spec:
  ingressClassName: kong
  rules:
  - http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: location-tracker
            port:
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: visor-service
            port:
              number: 80
