apiVersion: v1
kind: Service
metadata:
  name: central-director
  namespace: backend
spec:
  selector:
    app: central-director
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
    name: http
  type: ClusterIP # only accessible within the cluster
